# Generated by Django 3.0.4 on 2020-04-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20200402_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
