# Generated by Django 3.0.4 on 2020-03-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenta', '0002_auto_20200328_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
    ]
